In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Dataset-2.xlsx')

In [3]:
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("-", "_")
df.columns = df.columns.str.lower()
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

In [4]:
df.tail()

,item,2020_21,2021_22,2022_23_(base_2011_12),2022_23_(base_2022_23),2023_24,2024_25
12,Household sector,4505626,4742333,5010475,5225437,5963550,6900602
13,Gross financial saving,3067021,2611974,2927604,2982279,3575657,3828361
14,Less financial liabilities,737350,899270,1596485,1596483,1879000,1571242
15,Saving in physical assets,2135450,2968302,3614851,3674635,4094766,4425126
16,Saving in the form of gold and silver ornaments,40505,61327,64504,165006,172127,218357

In [5]:
df.head()

,item,2020_21,2021_22,2022_23_(base_2011_12),2022_23_(base_2022_23),2023_24,2024_25
0,Gross Savings,5786929,7363103,8244048,7772917,9517450,11113324
1,Non-financial corporations,2088896,2733126,2976375,2259962,2880429,3207128
2,Public non-financial corporations,233567,312407,331867,346285,465394,472147
3,Departmental enterprises,49820,57940,67417,60990,66298,68023
4,Non-departmental enterprises,183747,254467,264450,285295,399096,404123

In [6]:
df.shape

(17, 7)

In [7]:
df.columns

Index(['item', '2020_21', '2021_22', '2022_23_(base_2011_12)',
       '2022_23_(base_2022_23)', '2023_24', '2024_25'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   item                    17 non-null     str
 1   2020_21                 17 non-null     int64
 2   2021_22                 17 non-null     int64
 3   2022_23_(base_2011_12)  17 non-null     int64
 4   2022_23_(base_2022_23)  17 non-null     int64
 5   2023_24                 17 non-null     int64
 6   2024_25                 17 non-null     int64
dtypes: int64(6), str(1)
memory usage: 1.1 KB

In [9]:
df.sort_values(by='2024_25', ascending=False)

,item,2020_21,2021_22,2022_23_(base_2011_12),2022_23_(base_2022_23),2023_24,2024_25
0,Gross Savings,5786929,7363103,8244048,7772917,9517450,11113324
12,Household sector,4505626,4742333,5010475,5225437,5963550,6900602
15,Saving in physical assets,2135450,2968302,3614851,3674635,4094766,4425126
13,Gross financial saving,3067021,2611974,2927604,2982279,3575657,3828361
1,Non-financial corporations,2088896,2733126,2976375,2259962,2880429,3207128
5,Private non-financial corporations,1855329,2420719,2644507,1913677,2415036,2734981
14,Less financial liabilities,737350,899270,1596485,1596483,1879000,1571242
6,Financial corporations,513845,591002,769821,879103,993641,1109900
7,Public financial corporations,280288,359568,464221,459701,535510,590172
9,Non-departmental enterprises,272857,352996,457498,456976,532929,587412
10,Private financial corporations,233557,231435,305600,419402,458132,519728
2,Public non-financial corporations,233567,312407,331867,346285,465394,472147
4,Non-departmental enterprises,183747,254467,264450,285295,399096,404123
16,Saving in the form of gold and silver ornaments,40505,61327,64504,165006,172127,218357
3,Departmental enterprises,49820,57940,67417,60990,66298,68023
8,Departmental enterprises,7431,6572,6723,2725,2580,2761
11,General Government,-1321438,-703359,-512622,-591585,-320171,-104305

In [10]:
df.describe()

,2020_21,2021_22,2022_23_(base_2011_12),2022_23_(base_2022_23),2023_24,2024_25
count,17.00,17.00,17.00,17.00,17.00,17.00
mean,"1,215,928.24","1,486,069.53","1,719,636.71","1,641,722.82","1,978,319.06","2,214,651.88"
std,"1,824,854.45","2,095,454.91","2,296,723.97","2,201,852.88","2,611,331.54","3,008,967.14"
min,"-1,321,438.00","-703,359.00","-512,622.00","-591,585.00","-320,171.00","-104,305.00"
25%,"183,747.00","231,435.00","264,450.00","285,295.00","399,096.00","404,123.00"
50%,"280,288.00","359,568.00","464,221.00","459,701.00","535,510.00","590,172.00"
75%,"2,088,896.00","2,611,974.00","2,927,604.00","2,259,962.00","2,880,429.00","3,207,128.00"
max,"5,786,929.00","7,363,103.00","8,244,048.00","7,772,917.00","9,517,450.00","11,113,324.00"